apiVersion: apps/v1
kind: Deployment
metadata:
  name: insureme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insureme
  template:
    metadata:
      labels:
        app: insureme
    spec:
      containers:
      - name: insureme
        image: rihan297/demohealthcare:1.0   # ✅ must match Docker Hub image
        ports:
        - containerPort: 8082                # ✅ app inside container listens here
        imagePullPolicy: Always

apiVersion: v1
kind: Service
metadata:
  name: insureme
spec:
  type: LoadBalancer         # ✅ easier for external access
  selector:
    app: insureme
  ports:
    - protocol: TCP
      port: 8082             # ✅ external port
      targetPort: 8082       # ✅ container port
