apiVersion: apps/v1
kind: Deployment
metadata:
  name: insureme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insureme
  template:
    metadata:
      labels:
        app: insureme
    spec:
      containers:
        - name: insureme
          image: rihan297/demohealthcare:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080   # App listens here
---
apiVersion: v1
kind: Service
metadata:
  name: insureme
spec:
  type: LoadBalancer
  selector:
    app: insureme
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
