apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
        - name: medicure
          image: rihan297/demohealthcare:1.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: medicure-service
spec:
  type: NodePort
  selector:
    app: medicure
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8082
