apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-deployment
  labels:
    app: medicure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
      - name: medicure
        image: rihan297/demohelthcarerihan:1.0
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: medicure-service
spec:
  type: NodePort
  selector:
    app: medicure
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30080   # external port to access app
