apiVersion: apps/v1
kind: Deployment
metadata:
  name: insureme
  labels:
    app: insureme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insureme
  template:
    metadata:
      labels:
        app: insureme
    spec:
      containers:
        - name: insureme
          image: rihan297/demohealthcare:1.0
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: insureme
spec:
  type: NodePort   # 👈 Change this from LoadBalancer to NodePort
  selector:
    app: insureme
  ports:
    - port: 8082       # Service port
      targetPort: 8082 # Container port
      nodePort: 32080  # Fixed NodePort (can be any between 30000-32767)
